const menClothing = [
  "T-Shirt",
  "Polo Shirt",
  "Dress Shirt",
  "Casual Shirt",
  "Henley Shirt",
  "Tank Top",
  "Sweatshirt",
  "Hoodie",
  "Jacket",
  "Blazer",
  "Suit",
  "Overcoat",
  "Trench Coat",
  "Jeans",
  "Chinos",
  "Dress Pants",
  "Shorts",
  "Cargo Pants",
  "Joggers",
  "Sweatpants",
  "Boxers",
  "Briefs",
  "Trunks",
  "Socks",
  "Dress Shoes",
  "Sneakers",
  "Loafers",
  "Boots",
  "Sandals",
  "Watch",
  "Belt",
  "Tie",
  "Bow Tie",
  "Pocket Square",
  "Gloves",
  "Scarf",
  "Beanie",
  "Cap",
  "Sunglasses",
  "Backpack",
];

export default menClothing;
