const womenClothing = [
  "Blouse",
  "T-Shirt",
  "Tank Top",
  "Crop Top",
  "Sweatshirt",
  "Hoodie",
  "Cardigan",
  "Jacket",
  "Blazer",
  "Coat",
  "Trench Coat",
  "Dress",
  "Skirt",
  "Mini Skirt",
  "Midi Skirt",
  "Maxi Skirt",
  "Jeans",
  "Leggings",
  "Joggers",
  "Shorts",
  "Capris",
  "Palazzo Pants",
  "Jumpsuit",
  "Romper",
  "Bra",
  "Panties",
  "Lingerie Set",
  "Stockings",
  "Socks",
  "Heels",
  "Flats",
  "Sneakers",
  "Sandals",
  "Boots",
  "Watch",
  "Belt",
  "Scarf",
  "Gloves",
  "Hat",
  "Sunglasses",
  "Handbag",
  "Clutch",
  "Backpack",
  "Jewelry Set",
  "Earrings",
  "Necklace",
  "Bracelet",
  "Ring",
  "Hair Accessories",
  "Shawl",
];

export default womenClothing;
